name: Qodana Code Analysis

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: jetbrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_CONFIGURATIONS_TOKEN }}
        with:
          use-caches: false
          # İşte kilidi açacak olan emir: "Python müfettişini indir ve hataları görmezden gel"
          args: --linter,jetbrains/qodana-python-community:2024.1,--fail-threshold,99999
