name: Qodana Code Analysis

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    
    env:
      # Kırmızı Node.js uyarılarını susturma emri
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: jetbrains/qodana-action@v2023.3
        env:
          # Sizin Ayarlar > Secrets kısmına eklediğiniz o parolayı kullanıyoruz
          QODANA_TOKEN: ${{ secrets.QODANA_CONFIGURATIONS_TOKEN }}
